# =============================================================================
# dbt_project.yml for the Janaagraha dbt Project
# =============================================================================
# This file configures your dbt project, including:
# - Project name and version
# - Profile to use for connections (must match your profiles.yml)
# - Paths for models, seeds, macros, etc.
# - Model and seed schema/materialization settings
# - Clean targets for dbt clean
# - Flags for package/materialization overrides
# =============================================================================

name: 'Janaagraha'           # Project name (must be lowercase, matches models: section)
version: '1.0.0'             # Project version

profile: 'Janaagraha'        # Connection profile name (must match profiles.yml)

flags:
  require_explicit_package_overrides_for_builtin_materializations: false
  # Required for Elementary package compatibility with dbt 1.8+

# -----------------------------------------------------------------------------
# File/folder paths for dbt to find models, macros, seeds, etc.
# -----------------------------------------------------------------------------
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# -----------------------------------------------------------------------------
# Directories to be removed by `dbt clean`
# -----------------------------------------------------------------------------
clean-targets:
  - "target"
  - "dbt_packages"

# -----------------------------------------------------------------------------
# Model configuration
# -----------------------------------------------------------------------------
models:
  Janaagraha:  # Must match the `name:` field above
    property_tax_poc:
      +schema: property_tax_poc_prod           # All models in this folder go to this schema
      #+tags: ['property_tax']                 # (Optional) Add tags for selection
      +materialized: table                     # Materialize as tables by default
    grants_condition:
      #staging:
        #+schema: grants_condition_staging
        #+tags: ['grants_condition', 'staging']
        #+materialized: table
      marts:
        +schema: grants_condition_prod         # All marts models go to this schema
        +tags: ['grants_condition', 'marts']   # Add tags for selection
        +materialized: table                   # Materialize as tables by default
  elementary:
    +schema: "elementary"                      # Elementary package models go to this schema

# -----------------------------------------------------------------------------
# Seed configuration
# -----------------------------------------------------------------------------
seeds:
  Janaagraha:
    +schema: CF_Prod                           # All seeds (CSV files) go to this schema

# =============================================================================
# End of dbt_project.yml
#