
version: 2

models:
  - name: tax_sub_rate
    description: "Property Tax Submission rate"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
